// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type ChatsByIdResponse struct {
	Chat              string          `json:"chat"`
	DataSources       json.RawMessage `json:"data_sources"`
	Documents         json.RawMessage `json:"documents"`
	FollowUpQuestions json.RawMessage `json:"follow_up_questions"`
	Playbooks         json.RawMessage `json:"playbooks"`
	Questions         json.RawMessage `json:"questions"`
	Steps             json.RawMessage `json:"steps"`
	StyleGuides       json.RawMessage `json:"style_guides"`
	TabularReviews    json.RawMessage `json:"tabular_reviews"`
}

type ChatsCancelResponse struct {
	Message    string `json:"message"`
	QuestionId string `json:"questionId"`
	Status     string `json:"status"`
}

type ChatsCreateResponse struct {
	ChatId     string `json:"chat_id"`
	Message    string `json:"message"`
	QuestionId string `json:"question_id"`
	Status     string `json:"status"`
}

type ChatsDeleteResponse struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

type ChatsListItem struct {
	CreatedAt        string `json:"created_at"`
	FirstQuestion    string `json:"first_question"`
	Id               string `json:"id"`
	IsPinned         bool   `json:"is_pinned"`
	MessageCount     int    `json:"message_count"`
	Name             string `json:"name"`
	Owner            string `json:"owner"`
	PermissionLevel  string `json:"permission_level"`
	TimeTakenSeconds int    `json:"time_taken_seconds"`
	Type             string `json:"type"`
	UpdatedAt        string `json:"updated_at"`
}

type ChatsQuestionFilesItem struct {
	ContentType string `json:"contentType"`
	DocId       string `json:"docId"`
	Name        string `json:"name"`
}

type ChatsQuestionResultResponse struct {
	Answer            string          `json:"answer"`
	AnswerRaw         string          `json:"answerRaw"`
	CitationIds       json.RawMessage `json:"citationIds"`
	FollowUpQuestions json.RawMessage `json:"followUpQuestions"`
	Mode              json.RawMessage `json:"mode"`
	Question          string          `json:"question"`
	QuestionId        string          `json:"questionId"`
	Status            string          `json:"status"`
}

type ChatsQuestionStatusResponse struct {
	CreatedAt  string `json:"createdAt"`
	LastStepAt string `json:"lastStepAt"`
	QuestionId string `json:"questionId"`
	Status     string `json:"status"`
	StepCount  int    `json:"stepCount"`
	UpdatedAt  string `json:"updatedAt"`
}

type ChatsRenameResponse struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

type ContentDocumentsGetItem struct {
	ChunkIndex float64 `json:"chunkIndex"`
	PageNumber string  `json:"pageNumber"`
	Text       string  `json:"text"`
}

type ContentSearchSearchContentItem struct {
	ChunkId    string          `json:"chunkId"`
	ChunkIndex float64         `json:"chunkIndex"`
	Content    string          `json:"content"`
	DocId      string          `json:"docId"`
	DocName    string          `json:"docName"`
	Highlights json.RawMessage `json:"highlights"`
	PageNumber string          `json:"pageNumber"`
	Score      float64         `json:"score"`
}

type DownloadUrlDocumentsGetPresignedUrlResponse struct {
	Url string `json:"url"`
}

type FoldersCreateResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type FoldersDeleteResponse struct {
	DeletedCount float64 `json:"deletedCount"`
	Success      bool    `json:"success"`
}

type FoldersListItem struct {
	CreatedAt            string          `json:"created_at"`
	Description          string          `json:"description"`
	FileCount            float64         `json:"file_count"`
	FileSize             string          `json:"file_size"`
	Id                   string          `json:"id"`
	IsReady              bool            `json:"is_ready"`
	Name                 string          `json:"name"`
	ParentFolderId       string          `json:"parent_folder_id"`
	ParentFolderName     string          `json:"parent_folder_name"`
	SharedByMe           bool            `json:"shared_by_me"`
	SharedWithMe         bool            `json:"shared_with_me"`
	Status               string          `json:"status"`
	SubfolderCount       float64         `json:"subfolder_count"`
	Tags                 json.RawMessage `json:"tags"`
	TotalDescendantCount float64         `json:"total_descendant_count"`
	Type                 string          `json:"type"`
	UpdatedAt            string          `json:"updated_at"`
}

type FoldersProjectsRootItem struct {
	CreatedAt   string `json:"createdAt"`
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	UpdatedAt   string `json:"updatedAt"`
}

type MembersProjectsItem struct {
	Email           string `json:"email"`
	FirstName       string `json:"first_name"`
	Id              string `json:"id"`
	ImageUrl        string `json:"image_url"`
	LastName        string `json:"last_name"`
	PermissionLevel string `json:"permissionLevel"`
}

type PreSharePoliciesPreSharesCreatePolicyItem struct {
	ArtifactId   string `json:"artifactId"`
	ArtifactType string `json:"artifactType"`
}

type PreSharePoliciesPreSharesDeletePolicyResponse struct {
	Success bool `json:"success"`
}

type PreSharePoliciesPreSharesGetPolicyItem struct {
	ArtifactId   string `json:"artifactId"`
	ArtifactType string `json:"artifactType"`
}

type PreSharePoliciesPreSharesListPoliciesItem struct {
	AppliedCount          float64         `json:"appliedCount"`
	ArtifactCount         float64         `json:"artifactCount"`
	Artifacts             json.RawMessage `json:"artifacts"`
	BackfillExistingUsers bool            `json:"backfillExistingUsers"`
	ConditionType         string          `json:"conditionType"`
	ConditionValue        string          `json:"conditionValue"`
	CreatedAt             string          `json:"createdAt"`
	CreatedByUserId       string          `json:"createdByUserId"`
	DeliveryMode          string          `json:"deliveryMode"`
	DestinationType       string          `json:"destinationType"`
	FailedCount           float64         `json:"failedCount"`
	Id                    string          `json:"id"`
	IsEnabled             bool            `json:"isEnabled"`
	MatchedUsersCount     float64         `json:"matchedUsersCount"`
	Name                  string          `json:"name"`
	PermissionLevel       string          `json:"permissionLevel"`
	TargetProjectId       string          `json:"targetProjectId"`
	TargetProjectName     string          `json:"targetProjectName"`
	UpdatedAt             string          `json:"updatedAt"`
}

type PreSharePoliciesPreSharesTogglePolicyEnabledItem struct {
	ArtifactId   string `json:"artifactId"`
	ArtifactType string `json:"artifactType"`
}

type ProjectsCreateResponse struct {
	CreatedAt       string `json:"createdAt"`
	Description     string `json:"description"`
	Id              string `json:"id"`
	Name            string `json:"name"`
	PermissionLevel string `json:"permissionLevel"`
}

type ProjectsDeleteResponse struct {
	Deleted bool   `json:"deleted"`
	Id      string `json:"id"`
}

type ProjectsListItem struct {
	ClientNum         string `json:"client_num"`
	CreatedAt         string `json:"created_at"`
	Description       string `json:"description"`
	HiddenFromSidebar bool   `json:"hiddenFromSidebar"`
	Id                string `json:"id"`
	MatterNum         string `json:"matter_num"`
	Name              string `json:"name"`
	PermissionLevel   string `json:"permissionLevel"`
	PinnedAt          string `json:"pinnedAt"`
	SharingEnabled    bool   `json:"sharing_enabled"`
	UpdatedAt         string `json:"updated_at"`
}

type ProjectsRenameResponse struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updatedAt"`
}

type RevertPreSharesPolicyResponse struct {
	FailedCount   float64 `json:"failedCount"`
	PolicyId      string  `json:"policyId"`
	RevertedCount float64 `json:"revertedCount"`
	SkippedCount  float64 `json:"skippedCount"`
}

type SearchResourceFolderSearchItem struct {
	CreatedAt            string          `json:"created_at"`
	Description          string          `json:"description"`
	FileCount            float64         `json:"file_count"`
	FileSize             string          `json:"file_size"`
	Id                   string          `json:"id"`
	IsReady              bool            `json:"is_ready"`
	Name                 string          `json:"name"`
	ParentFolderId       string          `json:"parent_folder_id"`
	ParentFolderName     string          `json:"parent_folder_name"`
	SharedByMe           bool            `json:"shared_by_me"`
	SharedWithMe         bool            `json:"shared_with_me"`
	Status               string          `json:"status"`
	SubfolderCount       float64         `json:"subfolder_count"`
	Tags                 json.RawMessage `json:"tags"`
	TotalDescendantCount float64         `json:"total_descendant_count"`
	Type                 string          `json:"type"`
	UpdatedAt            string          `json:"updated_at"`
}

type T__schema0 struct {
	Children      json.RawMessage `json:"children"`
	Description   string          `json:"description"`
	DocumentCount string          `json:"documentCount"`
	Id            string          `json:"id"`
	Name          string          `json:"name"`
}

type error_BAD_REQUEST struct {
	Code    string          `json:"code"`
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type error_FORBIDDEN struct {
	Code    string          `json:"code"`
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type error_INTERNAL_SERVER_ERROR struct {
	Code    string          `json:"code"`
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type error_NOT_FOUND struct {
	Code    string          `json:"code"`
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}

type error_UNAUTHORIZED struct {
	Code    string          `json:"code"`
	Issues  json.RawMessage `json:"issues"`
	Message string          `json:"message"`
}
