// Copyright 2026 vera. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type DownloadRequest struct {
	DocIds    json.RawMessage `json:"doc_ids"`
	ProjectId string          `json:"project_id"`
	Ttl       int             `json:"ttl"`
	UsePdf    bool            `json:"use_pdf"`
}

type DownloadResponse struct {
	Urls json.RawMessage `json:"urls"`
}

type DownloadUrl struct {
	DocId     string `json:"doc_id"`
	ExpiresAt string `json:"expires_at"`
	Filename  string `json:"filename"`
	Url       string `json:"url"`
}

type FolderContents struct {
	Items  json.RawMessage `json:"items"`
	Limit  int             `json:"limit"`
	Offset int             `json:"offset"`
	Total  int             `json:"total"`
}

type FolderItem struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Size      int    `json:"size"`
	Type      string `json:"type"`
	UpdatedAt string `json:"updated_at"`
}

type FolderTree struct {
	Root json.RawMessage `json:"root"`
}

type FolderTreeNode struct {
	Children json.RawMessage `json:"children"`
	Id       string          `json:"id"`
	Name     string          `json:"name"`
	Type     string          `json:"type"`
}

type Member struct {
	Email string `json:"email"`
	Id    string `json:"id"`
	Name  string `json:"name"`
	Role  string `json:"role"`
}

type MemberList struct {
	Members json.RawMessage `json:"members"`
}

type Project struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

type ProjectList struct {
	Projects json.RawMessage `json:"projects"`
}

type QueryFile struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Size      int    `json:"size"`
	Type      string `json:"type"`
}

type QueryFiles struct {
	Files   json.RawMessage `json:"files"`
	QueryId string          `json:"query_id"`
}

type QueryRequest struct {
	FileIds   json.RawMessage `json:"file_ids"`
	FolderIds json.RawMessage `json:"folder_ids"`
	Mode      string          `json:"mode"`
	ProjectId string          `json:"project_id"`
	Query     string          `json:"query"`
}

type QueryResult struct {
	Answer    string          `json:"answer"`
	Citations json.RawMessage `json:"citations"`
	QueryId   string          `json:"query_id"`
	Sources   json.RawMessage `json:"sources"`
	Status    string          `json:"status"`
}

type QueryStatus struct {
	Progress  float64 `json:"progress"`
	QueryId   string  `json:"query_id"`
	Status    string  `json:"status"`
	UpdatedAt string  `json:"updated_at"`
}

type QuerySubmitResponse struct {
	CreatedAt string `json:"created_at"`
	QueryId   string `json:"query_id"`
	Status    string `json:"status"`
}

type SearchResult struct {
	FolderId  string  `json:"folder_id"`
	Id        string  `json:"id"`
	ProjectId string  `json:"project_id"`
	Score     float64 `json:"score"`
	Snippet   string  `json:"snippet"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

type SearchResults struct {
	Limit   int             `json:"limit"`
	Offset  int             `json:"offset"`
	Results json.RawMessage `json:"results"`
	Total   int             `json:"total"`
}
