// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/AIF-Of-Counsel/august-cli/internal/cli"
	"github.com/AIF-Of-Counsel/august-cli/internal/client"
	"github.com/AIF-Of-Counsel/august-cli/internal/cliutil"
	"github.com/AIF-Of-Counsel/august-cli/internal/config"
	"github.com/AIF-Of-Counsel/august-cli/internal/mcp/cobratree"
	"github.com/AIF-Of-Counsel/august-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("chats_by-id",
			mcplib.WithDescription("Get a chat thread. Required: chatId. Returns the ChatsByIdResponse."),
			mcplib.WithString("chatId", mcplib.Required(), mcplib.Description("Chat id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chats/{chatId}", true, false, nil, []mcpParamBinding{{PublicName: "chatId", WireName: "chatId", Location: "path"}}, []string{"chatId"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_cancel",
			mcplib.WithDescription("Cancels a running or pending question. No-op if already in a terminal state. `question_id` is the chat_questions id returned by POST /chats. Required: question_id. Returns the new ChatsCancelResponse."),
			mcplib.WithString("question_id", mcplib.Required(), mcplib.Description("Question id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/chats/questions/{question_id}/cancel", false, false, nil, []mcpParamBinding{{PublicName: "question_id", WireName: "question_id", Location: "path"}}, []string{"question_id"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_create",
			mcplib.WithDescription("Submits a query and returns the chat and question ids. The answer is produced asynchronously — poll `GET /chats/{chatId}` for the result. Required: chat_id, prompt. Optional: file_ids (default: []), folder_ids (default: []), mode (default: [auto]) (plus 4 more)."),
			mcplib.WithString("chat_id", mcplib.Required(), mcplib.Description("Chat id")),
			mcplib.WithString("file_ids", mcplib.Description("File ids")),
			mcplib.WithString("folder_ids", mcplib.Description("Folder ids")),
			mcplib.WithString("mode", mcplib.Description("Mode")),
			mcplib.WithString("playbook_ids", mcplib.Description("Playbook ids")),
			mcplib.WithString("project_id", mcplib.Description("Project id")),
			mcplib.WithString("prompt", mcplib.Required(), mcplib.Description("Prompt")),
			mcplib.WithString("tabular_review_ids", mcplib.Description("Tabular review ids")),
			mcplib.WithString("workflow_name", mcplib.Description("Workflow name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/chats", false, false, nil, []mcpParamBinding{{PublicName: "chat_id", WireName: "chat_id", Location: "body"}, {PublicName: "file_ids", WireName: "file_ids", Location: "body"}, {PublicName: "folder_ids", WireName: "folder_ids", Location: "body"}, {PublicName: "mode", WireName: "mode", Location: "body"}, {PublicName: "playbook_ids", WireName: "playbook_ids", Location: "body"}, {PublicName: "project_id", WireName: "project_id", Location: "body"}, {PublicName: "prompt", WireName: "prompt", Location: "body"}, {PublicName: "tabular_review_ids", WireName: "tabular_review_ids", Location: "body"}, {PublicName: "workflow_name", WireName: "workflow_name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("chats_delete",
			mcplib.WithDescription("Permanently deletes a chat and all its messages (FK cascade). Caller must be the chat owner. Irreversible. Required: chatId. Returns the ChatsDeleteResponse. Destructive."),
			mcplib.WithString("chatId", mcplib.Required(), mcplib.Description("Chat id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/chats/{chatId}", false, false, nil, []mcpParamBinding{{PublicName: "chatId", WireName: "chatId", Location: "path"}}, []string{"chatId"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_list",
			mcplib.WithDescription("List chats. Optional: limit (default: 20), cursor, projectId (plus 5 more). Returns array of ChatsListItem."),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithString("cursor", mcplib.Description("Cursor")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("search", mcplib.Description("Search")),
			mcplib.WithString("chatTypes", mcplib.Description("Chat types")),
			mcplib.WithString("modes", mcplib.Description("Modes")),
			mcplib.WithNumber("minutesAgo", mcplib.Description("Minutes ago")),
			mcplib.WithString("tagIds", mcplib.Description("Tag ids")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chats", true, false, nil, []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query", Default: "20"}, {PublicName: "cursor", WireName: "cursor", Location: "query"}, {PublicName: "projectId", WireName: "projectId", Location: "query"}, {PublicName: "search", WireName: "search", Location: "query"}, {PublicName: "chatTypes", WireName: "chatTypes", Location: "query"}, {PublicName: "modes", WireName: "modes", Location: "query"}, {PublicName: "minutesAgo", WireName: "minutesAgo", Location: "query"}, {PublicName: "tagIds", WireName: "tagIds", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("chats_question-files",
			mcplib.WithDescription("Lists work-product documents generated by a genius-mode question (genius_outputs folders). Required: questionId. Returns array of ChatsQuestionFilesItem."),
			mcplib.WithString("questionId", mcplib.Required(), mcplib.Description("Question id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chats/questions/{questionId}/files", true, false, nil, []mcpParamBinding{{PublicName: "questionId", WireName: "questionId", Location: "path"}}, []string{"questionId"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_question-result",
			mcplib.WithDescription("Returns the answer, follow-up questions, and citation ids for a completed question. Citation excerpt resolution (doc name/text) is not yet available. Required: questionId."),
			mcplib.WithString("questionId", mcplib.Required(), mcplib.Description("Question id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chats/questions/{questionId}/result", true, false, nil, []mcpParamBinding{{PublicName: "questionId", WireName: "questionId", Location: "path"}}, []string{"questionId"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_question-status",
			mcplib.WithDescription("Polls the status of a submitted question, with a lightweight step-count progress signal. Required: questionId. Returns the ChatsQuestionStatusResponse."),
			mcplib.WithString("questionId", mcplib.Required(), mcplib.Description("Question id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chats/questions/{questionId}/status", true, false, nil, []mcpParamBinding{{PublicName: "questionId", WireName: "questionId", Location: "path"}}, []string{"questionId"}),
	)
	s.AddTool(
		mcplib.NewTool("chats_rename",
			mcplib.WithDescription("Renames a chat. Caller must be the chat owner. Required: chatId, name. Returns the updated ChatsRenameResponse."),
			mcplib.WithString("chatId", mcplib.Required(), mcplib.Description("Chat id")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/chats/{chatId}", false, false, nil, []mcpParamBinding{{PublicName: "chatId", WireName: "chatId", Location: "path"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{"chatId"}),
	)
	s.AddTool(
		mcplib.NewTool("content_search_search-content",
			mcplib.WithDescription("Full-text (BM25) search across the parsed text of documents the caller can access. Scope with folderIds and/or docIds; returns matching chunks with highlighted snippets. Required: q. Optional: docIds (default: []), folderIds (default: []), projectId (plus 1 more)."),
			mcplib.WithString("docIds", mcplib.Description("Doc ids")),
			mcplib.WithString("folderIds", mcplib.Description("Folder ids")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("q", mcplib.Required(), mcplib.Description("Q")),
			mcplib.WithNumber("topK", mcplib.Description("Top k")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/search/content", false, false, nil, []mcpParamBinding{{PublicName: "docIds", WireName: "docIds", Location: "body"}, {PublicName: "folderIds", WireName: "folderIds", Location: "body"}, {PublicName: "projectId", WireName: "projectId", Location: "body"}, {PublicName: "q", WireName: "q", Location: "body"}, {PublicName: "topK", WireName: "topK", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("files_content_documents-get",
			mcplib.WithDescription("Returns the parsed text of a document as ordered chunks. Paginate with startChunkIndex/limit; re-call with startChunkIndex = endChunkIndex + 1 while hasMore is true. Required: docId. Optional: startChunkIndex (default: 0), limit (default: 100), projectId."),
			mcplib.WithString("docId", mcplib.Required(), mcplib.Description("Doc id")),
			mcplib.WithNumber("startChunkIndex", mcplib.Description("Start chunk index")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/{docId}/content", true, false, nil, []mcpParamBinding{{PublicName: "docId", WireName: "docId", Location: "path"}, {PublicName: "startChunkIndex", WireName: "startChunkIndex", Location: "query", Default: "0"}, {PublicName: "limit", WireName: "limit", Location: "query", Default: "100"}, {PublicName: "projectId", WireName: "projectId", Location: "query"}}, []string{"docId"}),
	)
	s.AddTool(
		mcplib.NewTool("files_download-url_documents-get-presigned-url",
			mcplib.WithDescription("Get a document download URL. Required: docId. Optional: usePdf (default: false), ttl (default: 3600). Returns the DownloadUrlDocumentsGetPresignedUrlResponse."),
			mcplib.WithString("docId", mcplib.Required(), mcplib.Description("Doc id")),
			mcplib.WithBoolean("usePdf", mcplib.Description("Use pdf")),
			mcplib.WithNumber("ttl", mcplib.Description("Ttl")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/{docId}/download-url", true, false, nil, []mcpParamBinding{{PublicName: "docId", WireName: "docId", Location: "path"}, {PublicName: "usePdf", WireName: "usePdf", Location: "query", Default: "false"}, {PublicName: "ttl", WireName: "ttl", Location: "query", Default: "3600"}}, []string{"docId"}),
	)
	s.AddTool(
		mcplib.NewTool("folders_create",
			mcplib.WithDescription("Three positioning modes: subfolder (parentId), project root (projectId), or personal root (neither). Caller becomes owner. Required: name. Optional: description, parentId, projectId. Returns the new FoldersCreateResponse."),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithString("parentId", mcplib.Description("Parent id")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/folders", false, false, nil, []mcpParamBinding{{PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "parentId", WireName: "parentId", Location: "body"}, {PublicName: "projectId", WireName: "projectId", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_delete",
			mcplib.WithDescription("Soft-deletes one or more folders and their whole subtrees (owner-only). folderIds serialize as repeated query params. Required: folderIds. Returns the FoldersDeleteResponse. Destructive."),
			mcplib.WithString("folderIds", mcplib.Required(), mcplib.Description("Folder ids")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/folders", false, false, nil, []mcpParamBinding{{PublicName: "folderIds", WireName: "folderIds", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_list",
			mcplib.WithDescription("Folders (alphabetical) then files (paginated by cursor/limit). Omit parentFolderId (null) for the personal/project root. All inputs are optional query params; arrays (filterTagIds) serialize as repeated query params. Returns items[] plus total_folders, total_files, nextCursor. Optional: projectId, parentFolderId, cursor (plus 6 more)."),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("parentFolderId", mcplib.Description("Parent folder id")),
			mcplib.WithString("cursor", mcplib.Description("Cursor")),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithString("sortBy", mcplib.Description("Sort by")),
			mcplib.WithBoolean("sortDesc", mcplib.Description("Sort desc")),
			mcplib.WithString("filterTagIds", mcplib.Description("Filter tag ids")),
			mcplib.WithBoolean("includeFiles", mcplib.Description("Include files")),
			mcplib.WithBoolean("includeTags", mcplib.Description("Include tags")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/folders/contents", true, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "query"}, {PublicName: "parentFolderId", WireName: "parentFolderId", Location: "query"}, {PublicName: "cursor", WireName: "cursor", Location: "query"}, {PublicName: "limit", WireName: "limit", Location: "query", Default: "5000"}, {PublicName: "sortBy", WireName: "sortBy", Location: "query", Default: "name"}, {PublicName: "sortDesc", WireName: "sortDesc", Location: "query", Default: "false"}, {PublicName: "filterTagIds", WireName: "filterTagIds", Location: "query"}, {PublicName: "includeFiles", WireName: "includeFiles", Location: "query", Default: "true"}, {PublicName: "includeTags", WireName: "includeTags", Location: "query", Default: "true"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("folders_tree_folder",
			mcplib.WithDescription("Returns the recursive folder hierarchy rooted at folderId. Caller must have read access to the folder. Required: folderId."),
			mcplib.WithString("folderId", mcplib.Required(), mcplib.Description("Folder id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/folders/{folderId}/tree", true, false, nil, []mcpParamBinding{{PublicName: "folderId", WireName: "folderId", Location: "path"}}, []string{"folderId"}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_pre-shares-create-policy",
			mcplib.WithDescription("Create a pre-share policy. Required: artifacts, backfillExistingUsers, conditionType, conditionValue, deliveryMode, destinationType, isEnabled, name, permissionLevel, targetProjectId. Returns array of PreSharePoliciesPreSharesCreatePolicyItem."),
			mcplib.WithString("artifacts", mcplib.Required(), mcplib.Description("Artifacts")),
			mcplib.WithBoolean("backfillExistingUsers", mcplib.Required(), mcplib.Description("Backfill existing users")),
			mcplib.WithString("conditionType", mcplib.Required(), mcplib.Description("Condition type")),
			mcplib.WithString("conditionValue", mcplib.Required(), mcplib.Description("Condition value")),
			mcplib.WithString("deliveryMode", mcplib.Required(), mcplib.Description("Delivery mode")),
			mcplib.WithString("destinationType", mcplib.Required(), mcplib.Description("Destination type")),
			mcplib.WithBoolean("isEnabled", mcplib.Required(), mcplib.Description("Is enabled")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithString("permissionLevel", mcplib.Required(), mcplib.Description("Permission level")),
			mcplib.WithString("targetProjectId", mcplib.Required(), mcplib.Description("Target project id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/pre-share-policies", false, false, nil, []mcpParamBinding{{PublicName: "artifacts", WireName: "artifacts", Location: "body"}, {PublicName: "backfillExistingUsers", WireName: "backfillExistingUsers", Location: "body"}, {PublicName: "conditionType", WireName: "conditionType", Location: "body"}, {PublicName: "conditionValue", WireName: "conditionValue", Location: "body"}, {PublicName: "deliveryMode", WireName: "deliveryMode", Location: "body"}, {PublicName: "destinationType", WireName: "destinationType", Location: "body"}, {PublicName: "isEnabled", WireName: "isEnabled", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "permissionLevel", WireName: "permissionLevel", Location: "body"}, {PublicName: "targetProjectId", WireName: "targetProjectId", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_pre-shares-delete-policy",
			mcplib.WithDescription("Delete a pre-share policy. Required: policyId. Returns the PreSharePoliciesPreSharesDeletePolicyResponse. Destructive."),
			mcplib.WithString("policyId", mcplib.Required(), mcplib.Description("Policy id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/pre-share-policies/{policyId}", false, false, nil, []mcpParamBinding{{PublicName: "policyId", WireName: "policyId", Location: "path"}}, []string{"policyId"}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_pre-shares-get-policy",
			mcplib.WithDescription("Get a pre-share policy. Required: policyId. Returns array of PreSharePoliciesPreSharesGetPolicyItem."),
			mcplib.WithString("policyId", mcplib.Required(), mcplib.Description("Policy id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/pre-share-policies/{policyId}", true, false, nil, []mcpParamBinding{{PublicName: "policyId", WireName: "policyId", Location: "path"}}, []string{"policyId"}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_pre-shares-list-policies",
			mcplib.WithDescription("List pre-share policies. Returns array of PreSharePoliciesPreSharesListPoliciesItem."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/pre-share-policies", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_pre-shares-toggle-policy-enabled",
			mcplib.WithDescription("Enable or disable a pre-share policy. Required: policyId, isEnabled. Returns array of PreSharePoliciesPreSharesTogglePolicyEnabledItem."),
			mcplib.WithString("policyId", mcplib.Required(), mcplib.Description("Policy id")),
			mcplib.WithBoolean("isEnabled", mcplib.Required(), mcplib.Description("Is enabled")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/pre-share-policies/{policyId}", false, false, nil, []mcpParamBinding{{PublicName: "policyId", WireName: "policyId", Location: "path"}, {PublicName: "isEnabled", WireName: "isEnabled", Location: "body"}}, []string{"policyId"}),
	)
	s.AddTool(
		mcplib.NewTool("pre-share-policies_revert_pre-shares-policy",
			mcplib.WithDescription("Revert applied deliveries for a pre-share policy. Required: policyId, confirm. Returns the new RevertPreSharesPolicyResponse."),
			mcplib.WithString("policyId", mcplib.Required(), mcplib.Description("Policy id")),
			mcplib.WithBoolean("confirm", mcplib.Required(), mcplib.Description("Confirm")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/pre-share-policies/{policyId}/revert", false, false, nil, []mcpParamBinding{{PublicName: "policyId", WireName: "policyId", Location: "path"}, {PublicName: "confirm", WireName: "confirm", Location: "body"}}, []string{"policyId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_create",
			mcplib.WithDescription("Creates a new project owned by the caller. The caller is added as the project owner. Required: name. Optional: clientNum, description, intelligencePrompt (plus 2 more). Returns the new ProjectsCreateResponse."),
			mcplib.WithString("clientNum", mcplib.Description("Client num")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("intelligencePrompt", mcplib.Description("Intelligence prompt")),
			mcplib.WithString("matterNum", mcplib.Description("Matter num")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithBoolean("sharingEnabled", mcplib.Description("Sharing enabled")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/projects", false, false, nil, []mcpParamBinding{{PublicName: "clientNum", WireName: "clientNum", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "intelligencePrompt", WireName: "intelligencePrompt", Location: "body"}, {PublicName: "matterNum", WireName: "matterNum", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "sharingEnabled", WireName: "sharingEnabled", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("projects_delete",
			mcplib.WithDescription("Permanently deletes a project and its resource links (chats and folders survive as personal resources). Destructive and irreversible; pass confirm=true. Required: projectId. Optional: confirm (default: false). Returns the ProjectsDeleteResponse."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithBoolean("confirm", mcplib.Description("Confirm")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/projects/{projectId}", false, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}, {PublicName: "confirm", WireName: "confirm", Location: "query", Default: "false"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_list",
			mcplib.WithDescription("Returns every project the authenticated user can access, most recently updated first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/projects", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("projects_rename",
			mcplib.WithDescription("Renames a project. Caller must be the project owner. Required: projectId, name. Returns the updated ProjectsRenameResponse."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/projects/{projectId}", false, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_folders_projects-root",
			mcplib.WithDescription("Lists the top-level folders (data sources) the project is anchored to. Caller must be a project member. Required: projectId. Returns array of FoldersProjectsRootItem."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/projects/{projectId}/folders", true, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_members_projects",
			mcplib.WithDescription("Returns every member of the project with their permission level. Caller must be a project member. Required: projectId."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/projects/{projectId}/members", true, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("search_resource_folder-search",
			mcplib.WithDescription("Name search across the accessible folder tree. Pass projectId (optional query param) to scope to a project; omit for the caller's personal workspace. Returns a flat array of folder/file hits. Required: query. Optional: projectId, scope (default: folders), parentFolderId."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Query")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("scope", mcplib.Description("Scope")),
			mcplib.WithString("parentFolderId", mcplib.Description("Parent folder id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/search", true, false, nil, []mcpParamBinding{{PublicName: "query", WireName: "query", Location: "query"}, {PublicName: "projectId", WireName: "projectId", Location: "query"}, {PublicName: "scope", WireName: "scope", Location: "query", Default: "folders"}, {PublicName: "parentFolderId", WireName: "parentFolderId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("workflows_create-from-prompt",
			mcplib.WithDescription("Generates a runnable workflow draft from a natural-language prompt and saves it. Reuse idempotencyKey to dedupe retries. Trigger provisioning is best-effort — failures return in triggerWarnings. Required: prompt. Optional: idempotencyKey, projectId. Returns array of string."),
			mcplib.WithString("idempotencyKey", mcplib.Description("Idempotency key")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("prompt", mcplib.Required(), mcplib.Description("Prompt")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/workflows", false, false, nil, []mcpParamBinding{{PublicName: "idempotencyKey", WireName: "idempotencyKey", Location: "body"}, {PublicName: "projectId", WireName: "projectId", Location: "body"}, {PublicName: "prompt", WireName: "prompt", Location: "body"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	Default    string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set it with: august-pp-cli auth set-token <token> or export AUGUST_AUTHORIZATION=\"your-token-here\"" +
					"\n      Run 'august-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: august-pp-cli auth set-token <token> or export AUGUST_AUTHORIZATION=\"your-token-here\"" +
					"\n      Run 'august-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set it with: august-pp-cli auth set-token <token> or export AUGUST_AUTHORIZATION=\"your-token-here\"" +
					"\n      Run 'august-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "august-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "august-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "august",
		"description": "Programmatic access to August. Authenticate every request with a Clerk API key: `Authorization: Bearer ak_...`.",
		"archetype":   "content",
		"tool_count":  30,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion august-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "AUGUST_AUTHORIZATION",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "chats",
				"description": "Manage chats",
				"endpoints":   []string{"by-id", "cancel", "create", "delete", "list", "question-files", "question-result", "question-status", "rename"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "content_search",
				"description": "Manage content search",
				"endpoints":   []string{"search-content"},
				"searchable":  true,
			},
			{
				"name":        "files",
				"description": "Manage files",
				"endpoints":   []string{},
			},
			{
				"name":        "folders",
				"description": "Manage folders",
				"endpoints":   []string{"create", "delete", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "pre-share-policies",
				"description": "Manage pre share policies",
				"endpoints":   []string{"pre-shares-create-policy", "pre-shares-delete-policy", "pre-shares-get-policy", "pre-shares-list-policies", "pre-shares-toggle-policy-enabled"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "projects",
				"description": "Manage projects",
				"endpoints":   []string{"create", "delete", "list", "rename"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "search_resource",
				"description": "Manage search resource",
				"endpoints":   []string{"folder-search"},
				"searchable":  true,
			},
			{
				"name":        "workflows",
				"description": "Manage workflows",
				"endpoints":   []string{"create-from-prompt"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass cursor parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
