// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChatsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "chats",
		Short:       "List, get, create, update, and delete chats",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newChatsByIdCmd(flags))
	cmd.AddCommand(newChatsCancelCmd(flags))
	cmd.AddCommand(newChatsCreateCmd(flags))
	cmd.AddCommand(newChatsDeleteCmd(flags))
	cmd.AddCommand(newChatsListCmd(flags))
	cmd.AddCommand(newChatsQuestionFilesCmd(flags))
	cmd.AddCommand(newChatsQuestionResultCmd(flags))
	cmd.AddCommand(newChatsQuestionStatusCmd(flags))
	cmd.AddCommand(newChatsRenameCmd(flags))
	return cmd
}
