// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFilesDownloadUrlCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "download-url",
		Short:       "Get download url for files",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFilesDownloadUrlDocumentsGetPresignedUrlCmd(flags))
	return cmd
}
