// Copyright 2026 vera. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFoldersTreeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tree",
		Short:       "Get tree for folders",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFoldersTreeGetFolderCmd(flags))
	return cmd
}
