// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFoldersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "folders",
		Short:       "List, create, and delete folders",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFoldersCreateCmd(flags))
	cmd.AddCommand(newFoldersDeleteCmd(flags))
	cmd.AddCommand(newFoldersListCmd(flags))
	cmd.AddCommand(newFoldersTreeCmd(flags))
	return cmd
}
