// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFoldersListCmd(flags *rootFlags) *cobra.Command {
	var flagProjectId string
	var flagParentFolderId string
	var flagCursor string
	var flagLimit int
	var flagSortBy string
	var flagSortDesc bool
	var flagFilterTagIds string
	var flagIncludeFiles bool
	var flagIncludeTags bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "Folders (alphabetical) then files (paginated by cursor/limit). Omit parentFolderId (null) for the personal/project root.",
		Example:     "  august-pp-cli folders list",
		Annotations: map[string]string{"pp:endpoint": "folders.list", "pp:method": "GET", "pp:path": "/folders/contents", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"name", "created_at", "updated_at", "file_size", "file_type"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSortBy, "sort-by", allowedSortBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/folders/contents"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "folders", path, map[string]string{
				"projectId":      formatCLIParamValue(flagProjectId),
				"parentFolderId": formatCLIParamValue(flagParentFolderId),
				"cursor":         formatCLIParamValue(flagCursor),
				"limit":          formatCLIParamValue(flagLimit),
				"sortBy":         formatCLIParamValue(flagSortBy),
				"sortDesc":       formatCLIParamValue(flagSortDesc),
				"filterTagIds":   formatCLIParamValue(flagFilterTagIds),
				"includeFiles":   formatCLIParamValue(flagIncludeFiles),
				"includeTags":    formatCLIParamValue(flagIncludeTags),
			}, nil, flagAll, "cursor", "cursor", "limit", "nextCursor", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagProjectId, "project-id", "", "Project id")
	cmd.Flags().StringVar(&flagParentFolderId, "parent-folder-id", "", "Parent folder id")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor")
	cmd.Flags().IntVar(&flagLimit, "limit", 5000, "Limit")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "name", "Sort by (one of: name, created_at, updated_at, file_size, file_type)")
	cmd.Flags().BoolVar(&flagSortDesc, "sort-desc", false, "Sort desc")
	cmd.Flags().StringVar(&flagFilterTagIds, "filter-tag-ids", "", "Filter tag ids")
	cmd.Flags().BoolVar(&flagIncludeFiles, "include-files", true, "Include files")
	cmd.Flags().BoolVar(&flagIncludeTags, "include-tags", true, "Include tags")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
