// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPreSharePoliciesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pre-share-policies",
		Short:       "Manage pre share policies",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPreSharePoliciesPreSharesCreatePolicyCmd(flags))
	cmd.AddCommand(newPreSharePoliciesPreSharesDeletePolicyCmd(flags))
	cmd.AddCommand(newPreSharePoliciesPreSharesGetPolicyCmd(flags))
	cmd.AddCommand(newPreSharePoliciesPreSharesListPoliciesCmd(flags))
	cmd.AddCommand(newPreSharePoliciesPreSharesTogglePolicyEnabledCmd(flags))
	cmd.AddCommand(newPreSharePoliciesRevertCmd(flags))
	return cmd
}
