// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newPreSharePoliciesPreSharesCreatePolicyCmd(flags *rootFlags) *cobra.Command {
	var bodyArtifacts string
	var bodyBackfillExistingUsers string
	var bodyConditionType string
	var bodyConditionValue string
	var bodyDeliveryMode string
	var bodyDestinationType string
	var bodyIsEnabled string
	var bodyName string
	var bodyPermissionLevel string
	var bodyTargetProjectId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "pre-shares-create-policy",
		Aliases:     []string{"create"},
		Short:       "Create a pre-share policy",
		Example:     "  august-pp-cli pre-share-policies pre-shares-create-policy --condition-type organization_membership",
		Annotations: map[string]string{"pp:endpoint": "pre-share-policies.pre-shares-create-policy", "pp:method": "POST", "pp:path": "/pre-share-policies"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("artifacts") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "artifacts")
				}
				if !cmd.Flags().Changed("backfill-existing-users") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "backfill-existing-users")
				}
				if !cmd.Flags().Changed("condition-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "condition-type")
				}
				if !cmd.Flags().Changed("condition-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "condition-value")
				}
				if !cmd.Flags().Changed("delivery-mode") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "delivery-mode")
				}
				if !cmd.Flags().Changed("destination-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "destination-type")
				}
				if !cmd.Flags().Changed("is-enabled") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "is-enabled")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("permission-level") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "permission-level")
				}
				if !cmd.Flags().Changed("target-project-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "target-project-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/pre-share-policies"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyArtifacts != "" {
					var parsedArtifacts any
					if err := json.Unmarshal([]byte(bodyArtifacts), &parsedArtifacts); err != nil {
						return fmt.Errorf("parsing --artifacts JSON: %w", err)
					}
					body["artifacts"] = parsedArtifacts
				}
				if bodyBackfillExistingUsers != "" {
					parsedBackfillExistingUsers, err := strconv.ParseBool(bodyBackfillExistingUsers)
					if err != nil {
						return fmt.Errorf("parsing --backfill-existing-users as bool: %w", err)
					}
					body["backfillExistingUsers"] = parsedBackfillExistingUsers
				}
				if bodyConditionType != "" {
					body["conditionType"] = bodyConditionType
				}
				if bodyConditionValue != "" {
					body["conditionValue"] = bodyConditionValue
				}
				if bodyDeliveryMode != "" {
					body["deliveryMode"] = bodyDeliveryMode
				}
				if bodyDestinationType != "" {
					body["destinationType"] = bodyDestinationType
				}
				if bodyIsEnabled != "" {
					parsedIsEnabled, err := strconv.ParseBool(bodyIsEnabled)
					if err != nil {
						return fmt.Errorf("parsing --is-enabled as bool: %w", err)
					}
					body["isEnabled"] = parsedIsEnabled
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPermissionLevel != "" {
					body["permissionLevel"] = bodyPermissionLevel
				}
				if bodyTargetProjectId != "" {
					body["targetProjectId"] = bodyTargetProjectId
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "pre-share-policies", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "pre-share-policies", data, "artifacts")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pre-share-policies", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pre-share-policies", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pre-share-policies", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "pre-share-policies",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pre-share-policies", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "pre-share-policies", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyArtifacts, "artifacts", "", "Artifacts")
	cmd.Flags().StringVar(&bodyBackfillExistingUsers, "backfill-existing-users", "", "Backfill existing users")
	cmd.Flags().StringVar(&bodyConditionType, "condition-type", "", "Condition type")
	cmd.Flags().StringVar(&bodyConditionValue, "condition-value", "", "Condition value")
	cmd.Flags().StringVar(&bodyDeliveryMode, "delivery-mode", "", "Delivery mode")
	cmd.Flags().StringVar(&bodyDestinationType, "destination-type", "", "Destination type")
	cmd.Flags().StringVar(&bodyIsEnabled, "is-enabled", "", "Is enabled")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyPermissionLevel, "permission-level", "", "Permission level")
	cmd.Flags().StringVar(&bodyTargetProjectId, "target-project-id", "", "Target project id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
