// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "projects",
		Short:       "List, create, update, and delete projects",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsCreateCmd(flags))
	cmd.AddCommand(newProjectsDeleteCmd(flags))
	cmd.AddCommand(newProjectsListCmd(flags))
	cmd.AddCommand(newProjectsRenameCmd(flags))
	cmd.AddCommand(newProjectsFoldersCmd(flags))
	cmd.AddCommand(newProjectsMembersCmd(flags))
	return cmd
}
