// Copyright 2026 vera. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"august-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newQueriesPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyFileIds string
	var bodyFolderIds string
	var bodyMode string
	var bodyProjectId string
	var bodyQuery string

	cmd := &cobra.Command{
		Use:         "queries",
		Short:       "Submit a legal research or document analysis query in Genius Mode.",
		Long:        "Submit a legal research or document analysis query in Genius Mode.",
		Example:     "  august-pp-cli queries --query example-value",
		Annotations: map[string]string{"pp:endpoint": "queries.submit-query", "pp:method": "POST", "pp:path": "/api/v1/queries"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("query") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "query")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/queries"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyFileIds != "" {
				body["file_ids"] = cliutil.SplitCSV(bodyFileIds)
			}
			if bodyFolderIds != "" {
				body["folder_ids"] = cliutil.SplitCSV(bodyFolderIds)
			}
			if bodyMode != "" {
				body["mode"] = bodyMode
			}
			if bodyProjectId != "" {
				body["project_id"] = bodyProjectId
			}
			if bodyQuery != "" {
				body["query"] = bodyQuery
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "queries", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyFileIds, "file-ids", "", "File/document IDs to include in the query context")
	cmd.Flags().StringVar(&bodyFolderIds, "folder-ids", "", "Folder IDs to scope the query to")
	cmd.Flags().StringVar(&bodyMode, "mode", "research", "Query processing mode")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Project ID to scope the query to")
	cmd.Flags().StringVar(&bodyQuery, "query", "", "The natural language or structured query")

	// Wire sibling endpoints and sub-resources as subcommands
	{
		sub := newQueriesFilesCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}
	{
		sub := newQueriesResultCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}
	{
		sub := newQueriesStatusCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}

	return cmd
}
