// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "chats by-id", Description: "Get a chat thread", Group: "chats"},
	{Command: "chats cancel", Description: "Cancels a running or pending question. No-op if already in a terminal state. `question_id` is the chat_questions id returned by POST /chats.", Group: "chats"},
	{Command: "chats create", Description: "Submits a query and returns the chat and question ids. The answer is produced asynchronously — poll `GET /chats/{chatId}` for the result.", Group: "chats"},
	{Command: "chats delete", Description: "Permanently deletes a chat and all its messages (FK cascade). Caller must be the chat owner. Irreversible.", Group: "chats"},
	{Command: "chats list", Description: "List chats", Group: "chats"},
	{Command: "chats question-files", Description: "Lists work-product documents generated by a genius-mode question (genius_outputs folders).", Group: "chats"},
	{Command: "chats question-result", Description: "Returns the answer, follow-up questions, and citation ids for a completed question. Citation excerpt resolution (doc name/text) is not yet available.", Group: "chats"},
	{Command: "chats question-status", Description: "Polls the status of a submitted question, with a lightweight step-count progress signal.", Group: "chats"},
	{Command: "chats rename", Description: "Renames a chat. Caller must be the chat owner.", Group: "chats"},
	{Command: "content_search search-content", Description: "Full-text (BM25) search across the parsed text of documents the caller can access. Scope with folderIds and/or docIds; returns matching chunks with highlighted snippets.", Group: "content_search"},
	{Command: "files content documents-get", Description: "Returns the parsed text of a document as ordered chunks. Paginate with startChunkIndex/limit; re-call with startChunkIndex = endChunkIndex + 1 while hasMore is true.", Group: "files"},
	{Command: "files download-url documents-get-presigned-url", Description: "Get a document download URL", Group: "files"},
	{Command: "folders create", Description: "Three positioning modes: subfolder (parentId), project root (projectId), or personal root (neither). Caller becomes owner.", Group: "folders"},
	{Command: "folders delete", Description: "Soft-deletes one or more folders and their whole subtrees (owner-only). folderIds serialize as repeated query params.", Group: "folders"},
	{Command: "folders list", Description: "Folders (alphabetical) then files (paginated by cursor/limit). Omit parentFolderId (null) for the personal/project root. All inputs are optional query params; arrays (filterTagIds) serialize as repeated query params. Returns items[] plus total_folders, total_files, nextCursor.", Group: "folders"},
	{Command: "folders tree folder", Description: "Returns the recursive folder hierarchy rooted at folderId. Caller must have read access to the folder.", Group: "folders"},
	{Command: "pre-share-policies pre-shares-create-policy", Description: "Create a pre-share policy", Group: "pre-share-policies"},
	{Command: "pre-share-policies pre-shares-delete-policy", Description: "Delete a pre-share policy", Group: "pre-share-policies"},
	{Command: "pre-share-policies pre-shares-get-policy", Description: "Get a pre-share policy", Group: "pre-share-policies"},
	{Command: "pre-share-policies pre-shares-list-policies", Description: "List pre-share policies", Group: "pre-share-policies"},
	{Command: "pre-share-policies pre-shares-toggle-policy-enabled", Description: "Enable or disable a pre-share policy", Group: "pre-share-policies"},
	{Command: "pre-share-policies revert pre-shares-policy", Description: "Revert applied deliveries for a pre-share policy", Group: "pre-share-policies"},
	{Command: "projects create", Description: "Creates a new project owned by the caller. The caller is added as the project owner.", Group: "projects"},
	{Command: "projects delete", Description: "Permanently deletes a project and its resource links (chats and folders survive as personal resources). Destructive and irreversible; pass confirm=true.", Group: "projects"},
	{Command: "projects list", Description: "Returns every project the authenticated user can access, most recently updated first.", Group: "projects"},
	{Command: "projects rename", Description: "Renames a project. Caller must be the project owner.", Group: "projects"},
	{Command: "projects folders projects-root", Description: "Lists the top-level folders (data sources) the project is anchored to. Caller must be a project member.", Group: "projects"},
	{Command: "projects members projects", Description: "Returns every member of the project with their permission level. Caller must be a project member.", Group: "projects"},
	{Command: "search_resource folder-search", Description: "Name search across the accessible folder tree. Pass projectId (optional query param) to scope to a project; omit for the caller's personal workspace. Returns a flat array of folder/file hits.", Group: "search_resource"},
	{Command: "workflows create-from-prompt", Description: "Generates a runnable workflow draft from a natural-language prompt and saves it. Reuse idempotencyKey to dedupe retries. Trigger provisioning is best-effort — failures return in triggerWarnings.", Group: "workflows"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  august-pp-cli which "stale tickets"
  august-pp-cli which "bottleneck"
  august-pp-cli which --limit 1 "send message"
  august-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
