// Copyright 2026 justlyai and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "gid", "sid", "uid", "uuid", "guid", "name", "slug", "key", "code"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

func TestUpsertBatch_PreservesLargeIntegerResourceIDs(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": 55043301, "name": "large"}`),
		json.RawMessage(`{"id": 100, "name": "small"}`),
		json.RawMessage(`{"id": 7, "name": "tiny"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("numeric_ids", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	rows, err := s.DB().Query(`SELECT id FROM resources WHERE resource_type = ? ORDER BY CAST(id AS INTEGER)`, "numeric_ids")
	if err != nil {
		t.Fatalf("query resources: %v", err)
	}
	defer rows.Close()

	var got []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			t.Fatalf("scan id: %v", err)
		}
		got = append(got, id)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}
	want := []string{"7", "100", "55043301"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("resource ids = %v, want %v", got, want)
	}

	var literalMatches int
	if err := s.DB().QueryRow(
		`SELECT COUNT(*) FROM resources WHERE resource_type = ? AND id IN ('55043301', '100', '7')`,
		"numeric_ids",
	).Scan(&literalMatches); err != nil {
		t.Fatalf("count literal id matches: %v", err)
	}
	if literalMatches != len(items) {
		t.Fatalf("literal id matches = %d, want %d", literalMatches, len(items))
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

func TestSearchQuotesFTSQuerySyntax(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ip", "value": "10.0.0.1"}`),
		json.RawMessage(`{"id": "cidr", "value": "172.16.192.0/18"}`),
		json.RawMessage(`{"id": "host", "value": "host.example.com"}`),
		json.RawMessage(`{"id": "email", "value": "user@example.com"}`),
		json.RawMessage(`{"id": "mac", "value": "aa:bb:cc:dd:ee:ff"}`),
		json.RawMessage(`{"id": "hyphen", "value": "some-name"}`),
		json.RawMessage(`{"id": "multi", "value": "error with extra words before timeout"}`),
	}
	if stored, failed, err := s.UpsertBatch("search-regression", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	} else if failed != 0 || stored != len(items) {
		t.Fatalf("UpsertBatch stored=%d failed=%d, want stored=%d failed=0", stored, failed, len(items))
	}

	for _, query := range []string{
		"10.0.0.1",
		"172.16.192.0/18",
		"host.example.com",
		"user@example.com",
		"aa:bb:cc:dd:ee:ff",
		"some-name",
		"error timeout",
	} {
		results, err := s.Search(query, 10)
		if err != nil {
			t.Fatalf("Search(%q): %v", query, err)
		}
		if len(results) == 0 {
			t.Fatalf("Search(%q) returned no results", query)
		}
	}
}

// TestUpsertBatch_PopulatesChatsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed chats table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesChatsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("chats", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "chats").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "chats")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count chats: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("chats count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesContentSearchTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed content_search table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesContentSearchTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("content_search", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content_search").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content_search")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content_search: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("content_search count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesContentTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed content table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesContentTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "files_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "files_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "files_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("content", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("content count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandContentGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandContentGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "files_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("content", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content: %v", err)
	}
	if typed != 0 {
		t.Fatalf("content count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "files_id")
	}
}

// TestUpsertBatch_KeysContentByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysContentByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "files_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "files_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "files_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "files_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("content", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("content count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "files_id" = ?`, "content")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by files_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("files_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesDownloadUrlTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed download_url table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDownloadUrlTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "files_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "files_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "files_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("download_url", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "download_url").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "download_url")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count download_url: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("download_url count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandDownloadUrlGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandDownloadUrlGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "files_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("download_url", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "download_url").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "download_url")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count download_url: %v", err)
	}
	if typed != 0 {
		t.Fatalf("download_url count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "files_id")
	}
}

// TestUpsertBatch_KeysDownloadUrlByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysDownloadUrlByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "files_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "files_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "files_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "files_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("download_url", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "download_url").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "download_url")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count download_url: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("download_url count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "files_id" = ?`, "download_url")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by files_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("files_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesFoldersTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed folders table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesFoldersTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("folders", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "folders").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "folders")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count folders: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("folders count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

func TestSearchFoldersQuotesFTSQuerySyntax(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "typed-ip", "description": "10.0.0.1"}`),
		json.RawMessage(`{"id": "typed-host", "description": "host.example.com"}`),
		json.RawMessage(`{"id": "typed-multi", "description": "error with extra words before timeout"}`),
	}
	if stored, failed, err := s.UpsertBatch("folders", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	} else if failed != 0 || stored != len(items) {
		t.Fatalf("UpsertBatch stored=%d failed=%d, want stored=%d failed=0", stored, failed, len(items))
	}

	for _, query := range []string{
		"10.0.0.1",
		"host.example.com",
		"error timeout",
	} {
		results, err := s.SearchFolders(query, 10)
		if err != nil {
			t.Fatalf("SearchFolders(%q): %v", query, err)
		}
		if len(results) == 0 {
			t.Fatalf("SearchFolders(%q) returned no results", query)
		}
	}
}

// TestUpsertBatch_PopulatesTreeTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tree table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTreeTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "folders_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "folders_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "folders_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("tree", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tree").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tree")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tree: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tree count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandTreeGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandTreeGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "folders_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("tree", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tree").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tree")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tree: %v", err)
	}
	if typed != 0 {
		t.Fatalf("tree count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "folders_id")
	}
}

// TestUpsertBatch_KeysTreeByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysTreeByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "folders_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "folders_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "folders_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "folders_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("tree", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tree").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tree")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tree: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tree count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "folders_id" = ?`, "tree")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by folders_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("folders_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesPreSharePoliciesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed pre_share_policies table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPreSharePoliciesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("pre-share-policies", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "pre-share-policies").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "pre_share_policies")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count pre_share_policies: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("pre_share_policies count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesRevertTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed revert table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesRevertTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "pre_share_policies_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "pre_share_policies_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "pre_share_policies_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("revert", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "revert").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "revert")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count revert: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("revert count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandRevertGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandRevertGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "pre_share_policies_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("revert", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "revert").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "revert")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count revert: %v", err)
	}
	if typed != 0 {
		t.Fatalf("revert count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "pre_share_policies_id")
	}
}

// TestUpsertBatch_KeysRevertByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysRevertByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "pre_share_policies_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "pre_share_policies_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "pre_share_policies_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "pre_share_policies_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("revert", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "revert").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "revert")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count revert: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("revert count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "pre_share_policies_id" = ?`, "revert")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by pre_share_policies_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("pre_share_policies_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesProjectsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed projects table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesProjectsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("projects", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "projects").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "projects")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count projects: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("projects count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

func TestSearchProjectsQuotesFTSQuerySyntax(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "typed-ip", "description": "10.0.0.1"}`),
		json.RawMessage(`{"id": "typed-host", "description": "host.example.com"}`),
		json.RawMessage(`{"id": "typed-multi", "description": "error with extra words before timeout"}`),
	}
	if stored, failed, err := s.UpsertBatch("projects", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	} else if failed != 0 || stored != len(items) {
		t.Fatalf("UpsertBatch stored=%d failed=%d, want stored=%d failed=0", stored, failed, len(items))
	}

	for _, query := range []string{
		"10.0.0.1",
		"host.example.com",
		"error timeout",
	} {
		results, err := s.SearchProjects(query, 10)
		if err != nil {
			t.Fatalf("SearchProjects(%q): %v", query, err)
		}
		if len(results) == 0 {
			t.Fatalf("SearchProjects(%q) returned no results", query)
		}
	}
}

// TestUpsertBatch_PopulatesProjectsFoldersTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed projects_folders table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesProjectsFoldersTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "projects_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "projects_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "projects_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("projects_folders", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "projects_folders").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "projects_folders")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count projects_folders: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("projects_folders count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandProjectsFoldersGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandProjectsFoldersGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "projects_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("projects_folders", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "projects_folders").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "projects_folders")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count projects_folders: %v", err)
	}
	if typed != 0 {
		t.Fatalf("projects_folders count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "projects_id")
	}
}

// TestUpsertBatch_KeysProjectsFoldersByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysProjectsFoldersByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "projects_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "projects_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "projects_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "projects_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("projects_folders", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "projects_folders").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "projects_folders")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count projects_folders: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("projects_folders count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "projects_id" = ?`, "projects_folders")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by projects_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("projects_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesMembersTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed members table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMembersTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001", "projects_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-002", "projects_id": "test-parent-001"}`),
		json.RawMessage(`{"id": "test-003", "projects_id": "test-parent-001"}`),
	}
	if _, _, err := s.UpsertBatch("members", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "members").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "members")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count members: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("members count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_TypedFailureDoesNotStrandMembersGeneric exercises
// the savepoint isolation around the typed-table dispatch. The fixture omits
// the NOT NULL parent FK column so the typed insert fails; the savepoint
// rolls back only the typed projection. The generic resources row inserted
// just before must survive. Regression for issue #1392, where a single
// outer transaction caused typed-table failures to cascade and silently
// discard every successfully fetched API row.
func TestUpsertBatch_TypedFailureDoesNotStrandMembersGeneric(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Items deliberately omit "projects_id" so the typed NOT NULL
	// constraint fires.
	items := []json.RawMessage{
		json.RawMessage(`{"id": "orphan-001"}`),
		json.RawMessage(`{"id": "orphan-002"}`),
		json.RawMessage(`{"id": "orphan-003"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("members", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v (typed-table failure must not propagate)", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d (generic resources rows must land even when typed table fails)", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "members").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (savepoint rollback must not undo generic insert)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "members")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count members: %v", err)
	}
	if typed != 0 {
		t.Fatalf("members count = %d, want 0 (typed insert violated NOT NULL on %q)", typed, "projects_id")
	}
}

// TestUpsertBatch_KeysMembersByChildAndParent verifies dependent
// sub-collection rows with the same child id but different parent ids do not
// overwrite one another in either the generic resources table or the typed
// table. Regression for issue #2471.
func TestUpsertBatch_KeysMembersByChildAndParent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "shared_child", "projects_id": "parent_A"}`),
		json.RawMessage(`{"id": "shared", "projects_id": "child_parent_A"}`),
		json.RawMessage(`{"id": "shared_child", "projects_id": "parent_B"}`),
		json.RawMessage(`{"id": "other_child", "projects_id": "parent_A"}`),
	}
	stored, extractFailures, err := s.UpsertBatch("members", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != len(items) {
		t.Fatalf("stored = %d, want %d", stored, len(items))
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "members").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d (dependent rows collapsed on child id)", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "members")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count members: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("members count = %d, want %d (typed rows collapsed on child id)", typed, len(items))
	}

	var parentMatches int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE "projects_id" = ?`, "members")
	if err := db.QueryRow(parentQuery, "parent_A").Scan(&parentMatches); err != nil {
		t.Fatalf("count by projects_id: %v", err)
	}
	if parentMatches != 2 {
		t.Fatalf("projects_id=parent_A count = %d, want 2", parentMatches)
	}
}

// TestUpsertBatch_PopulatesSearchResourceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed search_resource table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSearchResourceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("search_resource", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "search_resource").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "search_resource")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count search_resource: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("search_resource count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

func TestSearchSearchResourceQuotesFTSQuerySyntax(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "typed-ip", "description": "10.0.0.1"}`),
		json.RawMessage(`{"id": "typed-host", "description": "host.example.com"}`),
		json.RawMessage(`{"id": "typed-multi", "description": "error with extra words before timeout"}`),
	}
	if stored, failed, err := s.UpsertBatch("search_resource", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	} else if failed != 0 || stored != len(items) {
		t.Fatalf("UpsertBatch stored=%d failed=%d, want stored=%d failed=0", stored, failed, len(items))
	}

	for _, query := range []string{
		"10.0.0.1",
		"host.example.com",
		"error timeout",
	} {
		results, err := s.SearchSearchResource(query, 10)
		if err != nil {
			t.Fatalf("SearchSearchResource(%q): %v", query, err)
		}
		if len(results) == 0 {
			t.Fatalf("SearchSearchResource(%q) returned no results", query)
		}
	}
}
